name: Check manifest for updates

on:
  push:
    branches: [ manifest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '3/5 * * * *'

concurrency: 
  group: check-manifest

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: definitions
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Check updated
        id: updated
        env:
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
          DEEPSIGHT_MANIFEST_NO_INCREMENT_VERSION: true
        run: node check.js
        continue-on-error: true

      - name: Save manifest.json artifact
        if: ${{ steps.updated.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: manifest.json

    outputs:
      updated: ${{ steps.updated.outcome }}

  definitions:
    needs: check
    if: ${{ needs.check.outputs.updated != 'failure' }}
    uses: ./.github/workflows/definitions.yml
    secrets: inherit

  deploy:
    needs: definitions
    uses: ./.github/workflows/deploy.yml  
    secrets: inherit

  cleanup:
    needs: [check, deploy]
    if: ${{ needs.check.outputs.updated != 'failure' }}
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
