name: Definitions
concurrency: ${{ github.ref }}

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  definitions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: definitions
          path: definitions

      - uses: actions/checkout@v4
        with:
          ref: generated
          path: generated

      # todo checkout a new branch for generated iconography
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^10.29.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        
      - name: Refresh token
        id: refresh_token
        env:
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
          DEEPSIGHT_MANIFEST_CLIENT_ID: ${{ vars.DEEPSIGHT_MANIFEST_CLIENT_ID }}
          DEEPSIGHT_MANIFEST_CLIENT_SECRET: ${{ secrets.DEEPSIGHT_MANIFEST_CLIENT_SECRET }}
          DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE: ${{ vars.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID: ${{ secrets.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID }}
        run: pnpm run refresh_token
        
      - name: Update access token
        if: ${{ steps.refresh_token.outputs != null && steps.refresh_token.outputs.access_token != null }}
        uses: action-pack/set-secret@v1
        with:
          name: 'DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN'
          value: ${{ steps.refresh_token.outputs.access_token }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
      - name: Update refresh token
        if: ${{ steps.refresh_token.outputs != null && steps.refresh_token.outputs.refresh_token != null }}
        uses: action-pack/set-secret@v1
        with:
          name: 'DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN'
          value: ${{ steps.refresh_token.outputs.refresh_token }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Download manifest artifact
        uses: actions/download-artifact@v4
        with:
          name: manifest
          path: definitions
        continue-on-error: true

      - name: Manifest
        env:
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
          DEEPSIGHT_MANIFEST_CLIENT_ID: ${{ vars.DEEPSIGHT_MANIFEST_CLIENT_ID }}
          DEEPSIGHT_MANIFEST_CLIENT_SECRET: ${{ secrets.DEEPSIGHT_MANIFEST_CLIENT_SECRET }}
          DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE: ${{ vars.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID: ${{ secrets.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID }}
          DEEPSIGHT_PATH: ${{ vars.DEEPSIGHT_PATH }}
          DEEPSIGHT_BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          DEEPSIGHT_BUILD_SHA: ${{ github.sha }}
        run: pnpm run manifest
        
      - name: Commit & Publish definitions
        run: |
          cd definitions
          git add .
          if [[ -n $(git diff --staged) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -m "Updated definitions"
            git push
            npm publish
          else
            echo "No changes to commit & publish"
          fi
          cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit static files
        run: |
          rm -rf docs/definitions
          rm -rf docs/testiny
          cd generated
          git rm -rf .
          cd ..
          cp -r docs/. generated/
          cd generated
          git add .
          if [[ -n $(git diff --staged) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -m "Updated static files"
            git push
          else
            echo "No changes to commit"
          fi
          cd ..
